### ISSUE TITLE
Trojan detected.

### ISSUE THREAD

**Issue by Bits-Bytes-354** [smp46/RightClickVirusTotal#2]
In a few antivirus software and Virus Total it was detected to be Trojan. Additionally, it didn't worked after running. Both of these increases my suspension of it being a Trojan.

**Comment by smp46** [comment]
Hey there, I appreciate the concern but VirusTotal commonly reports false positives, generally speaking if no more than 5 or 6 detections are present it will be a false positive. For future reference [here](https://www.virustotal.com/gui/file/eaa320aa5b2ca4cd37ece6968801241bd7e57be75e6a912d45034956589cfba2) is the report for the executable found in release 1.0. I suspect these engines picking it up as a trojan, will mark anything compiled using PyInstaller as such.

As for why it doesn't do anything, the program is intended to be added to the right click context menu on Windows, and therefore requires arguments to make the program do anything. I have updated the 1.0 release information with the following usage instructions:

## Basic Usage Instructions

With either the executable or the python script, arguments must be provided  _to get the program to do anything._

To use the program from the .py file on Windows:

`python .\RightClickVirusTotal_GUI_Windows.py "VirusTotalAPIKey" "FilePath"`

Ensure you replace the first argument, VirusTotalAPIKey, with your own API key and keep the quotation marks to ensure it is passed as a string. Then the second argument, FilePath, should be the whole path to the file.

For example:

`python .\RightClickVirusTotal_GUI_Windows.py "0010101010101abcdefq" "C:\Users\smp\Documents\RealVirus.exe"`

For the Windows executable file, the formatting of the arguments is the exact same however make sure to specify the .exe instead of .py file. Like this:

`.\RightClickVirusTotal.exe "0010101010101abcdefq" "C:\Users\smp\Documents\RealVirus.exe"`

**Comment by Bits-Bytes-354** [comment]
Thanks for resolving my suspicion and detailing the process of running it.
